metadata:
  output_dir: ${PROCESSED}pepsra
  sample_annotation: ${SRAMETA}annocomb_GSE52457.csv
  pipeline_interfaces: pipeline_interface_convert.yaml
  merge_table: ${SRAMETA}allmerge_GSE52457.csv

derived_columns: [data_source]

data_sources:
  SRA: "${SRARAW}{SRR}.sra"

subprojects:
  convert:
    metadata:
      pipeline_interfaces: "${CODE}pepsra/sra_convert/pipeline_interface_convert.yaml"